Repository TeamPophory/pophory-android, pull requests merged in 2023-08, with the labels that each got.

#234 [feature/ui_test]: UiTestSample 추가
  app/build.gradle.kts
  app/src/androidTest/kotlin/com/teampophory/pophory/SignUpActivityTest.kt
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/JUnit5Plugin.kt
  gradle/libs.versions.toml
Labels: ✨ Feature

#241 [feature/design-system-modularization] 디자인 시스템 모듈화
  app/build.gradle.kts
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/TeamScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/TermScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/LogoutDialog.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/SettingItem.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/WithdrawDialog.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/webview/WebViewActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/webview/WebViewScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  core/designsystem/.gitignore
  core/designsystem/build.gradle.kts
  core/designsystem/consumer-rules.pro
  core/designsystem/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/teampophory/pophory/designsystem/Color.kt
  core/designsystem/src/main/java/com/teampophory/pophory/designsystem/Theme.kt
  core/designsystem/src/main/java/com/teampophory/pophory/designsystem/Type.kt
  core/designsystem/src/main/res/drawable/ic_launcher_background.xml
  core/designsystem/src/main/res/drawable/ic_launcher_foreground.xml
  core/designsystem/src/main/res/font/pophory_font.xml
  core/designsystem/src/main/res/font/pretendard_bold.otf
  core/designsystem/src/main/res/font/pretendard_medium.otf
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
  core/designsystem/src/main/res/values-night/themes.xml
  core/designsystem/src/main/res/values/attrs.xml
  core/designsystem/src/main/res/values/colors.xml
  core/designsystem/src/main/res/values/shape.xml
  core/designsystem/src/main/res/values/themes.xml
  core/designsystem/src/main/res/values/type.xml
  settings.gradle.kts
Labels: 🐯 이현우, 🔨 Refactor

#243 [feature/setting-module] 설정화면 모듈 분리
  app/build.gradle.kts
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/navigation/DefaultNavigationProvider.kt
  core/common/src/main/java/com/teampophory/pophory/common/navigation/NavigationProvider.kt
  core/designsystem/src/main/res/drawable/ic_chevron_down.xml
  core/designsystem/src/main/res/drawable/ic_chevron_left.xml
  core/designsystem/src/main/res/drawable/ic_chevron_right.xml
  feature/setting/.gitignore
  feature/setting/build.gradle.kts
  feature/setting/consumer-rules.pro
  feature/setting/src/main/AndroidManifest.xml
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/SettingScreen.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/TeamScreen.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/TermScreen.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/component/LogoutDialog.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/component/SettingItem.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/component/WithdrawDialog.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/webview/WebViewActivity.kt
  feature/setting/src/main/java/com/teampophory/pophory/feature/setting/webview/WebViewScreen.kt
  feature/setting/src/main/res/drawable-xhdpi/img_team.png
  feature/setting/src/main/res/drawable-xxhdpi/img_team.png
  feature/setting/src/main/res/drawable-xxxhdpi/img_team.png
  feature/setting/src/main/res/drawable/img_team.png
  settings.gradle.kts
Labels: 🐯 이현우, 🔨 Refactor

#246 Update version
  README.md
  app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
  core/common/src/main/java/com/teampophory/pophory/common/lifecycle/Event.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ⚙ Setting

#248 [feature/home_viewmodel_refactor]:HomeViewModel refactoring 작업
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeViewState.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
Labels: 😼곽의진, 🔨 Refactor

#264 [feature/version-bump] Bump kotlin version to 1.9.10
  gradle/libs.versions.toml
Labels: 🐯 이현우, ⚙ Setting
