Repository TeamPophory/pophory-android, pull requests merged in 2023-06, with the labels that each got.

#6 [feature/github-configuration] Github 환경 설정
  .github/CODEOWNERS
  .github/auto_assign.yml
  .github/pull_request_template.md
  .github/workflows/develop_PR_builder.yml
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, 🦈서재원, ⚙ Setting, 🌏 Deploy

#10 [feature/add-dependency] dot-indicator 의존성 추가
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐣 안지현, ✨ Feature

#9 Update Issue template
  .github/ISSUE_TEMPLATE/pophory-issue-template.md 
Labels: 🦈서재원, 📃 Docs

#14 [feature/admob]: admob SDK 탑재 및 native 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/AdmobSampleActivity.kt
  app/src/main/java/com/teampophory/pophory/App.kt
  app/src/main/java/com/teampophory/pophory/util/ads/AdmobService.kt
  app/src/main/res/layout/activity_admob_sample.xml
  app/src/main/res/layout/admob_native_default.xml
  app/src/test/java/com/teampophory/pophory/ExampleUnitTest.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, 😼곽의진, ✨ Feature

#18 [feature/add-bottom-navigation-library] Bottom Navigation Library 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/SampleActivity.kt
  app/src/main/res/drawable/ic_hexagon.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/layout/activity_sample.xml
  bottomnavigation/.gitignore
  bottomnavigation/build.gradle.kts
  bottomnavigation/consumer-rules.pro
  bottomnavigation/proguard-rules.pro
  bottomnavigation/src/main/AndroidManifest.xml
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/BadgeHelper.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/BadgeItem.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/BezierView.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/CenterButton.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/NavigationShadow.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/SpaceItem.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/SpaceNavigationView.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/SpaceNavigationViewBehavior.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/SpaceOnClickListener.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/SpaceOnLongClickListener.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/util/DrawableEx.kt
  bottomnavigation/src/main/java/com/teampophory/pophory/bottomnavigation/util/Utils.kt
  bottomnavigation/src/main/res/drawable/near_me.xml
  bottomnavigation/src/main/res/drawable/white_ripple.xml
  bottomnavigation/src/main/res/layout/space_item_view.xml
  bottomnavigation/src/main/res/values/attrs.xml
  bottomnavigation/src/main/res/values/colors.xml
  bottomnavigation/src/main/res/values/dimens.xml
  bottomnavigation/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🐯 이현우, ✨ Feature

#20 :memo: Add README
  README.md
Labels: 🐯 이현우, 📃 Docs
