Repository TeamPophory/pophory-android, pull requests merged in 2023-10, with the labels that each got.

#308 [feature/onboarding-module] 온보딩 화면 모듈 분리 및 아키텍처 config
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingData.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/navigation/DefaultNavigationProvider.kt
  core/common/src/main/java/com/teampophory/pophory/common/navigation/NavigationProvider.kt
  data/auth/src/main/java/com/teampophory/pophory/data/auth/repository/DefaultAuthRepository.kt
  domain/auth/src/main/java/com/teampophory/pophory/auth/repository/AuthRepository.kt
  domain/auth/src/main/java/com/teampophory/pophory/auth/usecase/GetAutoLoginConfigurationUseCase.kt
  feature/onboarding/.gitignore
  feature/onboarding/build.gradle.kts
  feature/onboarding/consumer-rules.pro
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/teampophory/pophory/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/teampophory/pophory/onboarding/OnBoardingViewModel.kt
  feature/onboarding/src/main/java/com/teampophory/pophory/onboarding/adapter/OnBoardingViewPagerAdapter.kt
  feature/onboarding/src/main/java/com/teampophory/pophory/onboarding/model/OnBoardingData.kt
  feature/onboarding/src/main/res/drawable-xhdpi/img_onboarding01.png
  feature/onboarding/src/main/res/drawable-xhdpi/img_onboarding02.png
  feature/onboarding/src/main/res/drawable-xhdpi/img_onboarding03.png
  feature/onboarding/src/main/res/drawable-xhdpi/img_onboarding04.png
  feature/onboarding/src/main/res/drawable-xxhdpi/img_onboarding01.png
  feature/onboarding/src/main/res/drawable-xxhdpi/img_onboarding02.png
  feature/onboarding/src/main/res/drawable-xxhdpi/img_onboarding03.png
  feature/onboarding/src/main/res/drawable-xxhdpi/img_onboarding04.png
  feature/onboarding/src/main/res/drawable-xxxhdpi/img_onboarding01.png
  feature/onboarding/src/main/res/drawable-xxxhdpi/img_onboarding02.png
  feature/onboarding/src/main/res/drawable-xxxhdpi/img_onboarding03.png
  feature/onboarding/src/main/res/drawable-xxxhdpi/img_onboarding04.png
  feature/onboarding/src/main/res/drawable/bg_kakao_login_btn.xml
  feature/onboarding/src/main/res/drawable/ic_kakao.xml
  feature/onboarding/src/main/res/drawable/img_onboarding01.png
  feature/onboarding/src/main/res/drawable/img_onboarding02.png
  feature/onboarding/src/main/res/drawable/img_onboarding03.png
  feature/onboarding/src/main/res/drawable/img_onboarding04.png
  feature/onboarding/src/main/res/drawable/round_dot_indicator.xml
  feature/onboarding/src/main/res/layout/activity_on_boarding.xml
  feature/onboarding/src/main/res/layout/item_onboarding_viewpager.xml
  settings.gradle.kts
Labels: 🐯 이현우, 🔨 Refactor

#314 [Feature/qr] QR코드 인식 및 사진 불러오기 기능 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/add/AddPhotoBottomSheet.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/qr/ImageDownloader.kt
  app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/qr/QRViewModel.kt
  app/src/main/res/drawable/bg_round_8dp_gray20.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_qr_code.xml
  app/src/main/res/layout/activity_qr.xml
  app/src/main/res/layout/bottom_sheet_home_add_photo.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🦈서재원, ✨ Feature

#311 [Feature/admob_reward_video]: 리워드 비디오 광고 작업
  .github/workflows/develop_PR_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/config/ad/AdmobRewardedAdService.kt
  app/src/main/java/com/teampophory/pophory/config/di/AdModule.kt
  app/src/main/java/com/teampophory/pophory/domain/usecase/ConfigureMeUseCase.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/util/dialog/TwoButtonCommonDialog.kt
  app/src/main/res/drawable/bg_round_100dp_f5f5f5.xml
  app/src/main/res/drawable/ic_album_cover.xml
  app/src/main/res/layout/dialog_common_two_button.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt
  core/common/src/main/java/com/teampophory/pophory/common/ad/AdName.kt
  data/ad/.gitignore
  data/ad/build.gradle.kts
  data/ad/consumer-rules.pro
  data/ad/proguard-rules.pro
  data/ad/src/main/AndroidManifest.xml
  data/ad/src/main/java/com/teampophory/pophory/ad/model/AdConstantResponse.kt
  data/ad/src/main/java/com/teampophory/pophory/ad/repository/DefaultAdRepository.kt
  data/ad/src/main/java/com/teampophory/pophory/ad/service/AdService.kt
  domain/ad/.gitignore
  domain/ad/build.gradle.kts
  domain/ad/src/main/AndroidManifest.xml
  domain/ad/src/main/java/com/teampophory/pophory/ad/entity/AdIdentifier.kt
  domain/ad/src/main/java/com/teampophory/pophory/ad/repository/AdRepository.kt
  domain/ad/src/main/java/com/teampophory/pophory/ad/usecase/FetchAdConstantUseCase.kt
  domain/ad/src/main/java/com/teampophory/pophory/ad/usecase/GetAdConstantUseCase.kt
  domain/ad/src/main/java/com/teampophory/pophory/ad/usecase/SetAdConstantUseCase.kt
  settings.gradle.kts
Labels: 😼곽의진, ✨ Feature

#321 [Feature/qr_qa] 3차 스프린트 QR관련 qa 대응
  app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
  app/src/main/res/drawable/bg_round_100dp_gray30.xml
  app/src/main/res/drawable/bg_round_20dp_white.xml
  app/src/main/res/layout/activity_qr.xml
  app/src/main/res/layout/bottom_sheet_home_add_photo.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 BugFix, 🦈서재원, ✨ Feature
