Repository TeamPophory/pophory-android, pull requests merged in 2023-07, with the labels that each got.

#32 [feature/flipper-config] Flipper 설정하기
  app/build.gradle.kts
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/com/teampophory/pophory/FlipperInitializer.kt
  app/src/main/java/com/teampophory/pophory/App.kt
  app/src/release/java/FlipperInitializer.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ⚙ Setting

#37 [feature/kakao-configuration] Kakao 로그인 위한 기초 설정 + App Startup 설정
  .github/workflows/develop_PR_builder.yml
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/App.kt
  app/src/main/java/com/teampophory/pophory/config/initializer/AdInitializer.kt
  app/src/main/java/com/teampophory/pophory/config/initializer/KakaoSDKInitializer.kt
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt
  gradle/libs.versions.toml
  gradlew.bat
  keystore/debug.keystore
  settings.gradle.kts
Labels: 🐯 이현우, ⚙ Setting

#40 [feature/timber-config] Timber 로거 설정
  app/src/main/java/com/teampophory/pophory/config/initializer/AdInitializer.kt
  app/src/main/java/com/teampophory/pophory/config/initializer/CrashlyticsInitializer.kt
  app/src/main/java/com/teampophory/pophory/config/initializer/TimberInitializer.kt
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt
Labels: 🐯 이현우, ⚙ Setting

#38 [feature/bottomappbar] BottomNavigationView 생성 및 프래그먼트 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/my_page/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/store/StoreFragment.kt
  app/src/main/res/color/selc_bottom_nav_item.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_my.xml
  app/src/main/res/drawable/ic_my_drawer.xml
  app/src/main/res/drawable/shape_bottom_nav.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🦈서재원, ✨ Feature

#45 [feature/setup-utils] Util로 사용할 수 있는 core:common 모듈 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/SampleActivity.kt
  app/src/main/java/com/teampophory/pophory/config/ad/AdmobService.kt
  app/src/main/java/com/teampophory/pophory/feature/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/my_page/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/sample/AdmobSampleActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/store/StoreFragment.kt
  app/src/main/res/layout/activity_admob_sample.xml
  app/src/main/res/layout/activity_sample.xml
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt
  core/common/.gitignore
  core/common/build.gradle.kts
  core/common/consumer-rules.pro
  core/common/src/main/AndroidManifest.xml
  core/common/src/main/java/com/teampophory/pophory/common/context/ContextExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/fragment/FragmentExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/intent/ArgsExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/intent/ExtraExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/lifecycle/LifecycleExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/lifecycle/SingleLiveEvent.kt
  core/common/src/main/java/com/teampophory/pophory/common/time/TimeExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/view/Binding.kt
  core/common/src/main/java/com/teampophory/pophory/common/view/Pixel.kt
  core/common/src/main/java/com/teampophory/pophory/common/view/ViewExt.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🐯 이현우, ✨ Feature

#48 [feature/binding-error-fix] binding에서 참조되는 뷰를 기존 inflater에서 생성되는 걸 활용
  app/src/main/java/com/teampophory/pophory/feature/my_page/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/store/StoreFragment.kt
Labels: 🐞 BugFix, 🐯 이현우

#51 [feature/design-system] Color Design System 설정
  app/src/main/res/color/selc_bottom_nav_item.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🐯 이현우, ✨ Feature

#49 [feature/flexbox] 가로 세로 사진 정렬 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/data/repository/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumState.kt
  app/src/main/java/com/teampophory/pophory/feature/album/adapter/AlbumAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoList.kt
  app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
  app/src/main/java/com/teampophory/pophory/network/PhotoNetworkDataSource.kt
  app/src/main/java/com/teampophory/pophory/network/model/PhotoListResponse.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
  app/src/main/res/drawable/horizontal_example.xml
  app/src/main/res/drawable/vertical_example.xml
  app/src/main/res/layout/activity_admob_sample.xml
  app/src/main/res/layout/activity_album_list.xml
  app/src/main/res/layout/item_flexbox_layout.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 😼곽의진, ✨ Feature

#55 [feature/store] store view viewpager 및 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/my_page/MyPageFragment.kt
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_store_logo.xml
  app/src/main/res/drawable/img_album_cover.xml
  app/src/main/res/drawable/shape_bottom_nav.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_store_pager.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🦈서재원, ✨ Feature

#58 [feat/album]: Change Flexbox to LinearLayoutManager and Add Hilt
  .github/workflows/develop_PR_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/data/repository/PhotoRepositoryImpl.kt
  app/src/main/java/com/teampophory/pophory/di/NetworkModule.kt
  app/src/main/java/com/teampophory/pophory/di/RepositoryBindModule.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumState.kt
  app/src/main/java/com/teampophory/pophory/feature/album/adapter/AlbumAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
  app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoList.kt
  app/src/main/java/com/teampophory/pophory/feature/album/viewholder/AlbumViewHolder.kt
  app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
  app/src/main/java/com/teampophory/pophory/network/model/PhotoListResponse.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
  app/src/main/res/layout/activity_album_list.xml
  app/src/main/res/layout/item_horizontal_photo.xml
  app/src/main/res/layout/item_vertical_photo.xml
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt
  firebase/releaseNote.txt
Labels: 😼곽의진, ✨ Feature

#52 [feature/setting] 설정화면 제작
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/design/Color.kt
  app/src/main/java/com/teampophory/pophory/design/Theme.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/LogoutDialog.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/SettingItem.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/WithdrawDialog.kt
  app/src/main/res/drawable/ic_chevron_left.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/drawable/ic_close.xml
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/ComposePlugin.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/teampophory/pophory/common/compose/Border.kt
  core/common/src/main/java/com/teampophory/pophory/common/compose/DefaultPreview.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ✨ Feature

#62 [feature/kakao-login] 카카오 로그인 구현을 조금 더 쉽게 할 수 있는 KakaoAuthService 구현
  app/build.gradle.kts
  app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/NetModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/OAuthModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/PhotoModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/PreferencesModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/qualifier/Interceptor.kt
  app/src/main/java/com/teampophory/pophory/config/di/qualifier/OAuth.kt
  app/src/main/java/com/teampophory/pophory/data/local/DefaultPophoryDataStore.kt
  app/src/main/java/com/teampophory/pophory/data/local/PophoryDataStore.kt
  app/src/main/java/com/teampophory/pophory/data/network/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/.gitkeep
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/AuthResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/Token.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/UserAccountState.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/UserAuthentication.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/AuthService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/auth/AuthRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/auth/DefaultAuthRepository.kt
  app/src/main/java/com/teampophory/pophory/di/NetworkModule.kt
  app/src/main/java/com/teampophory/pophory/di/RepositoryBindModule.kt
  app/src/main/java/com/teampophory/pophory/domain/AuthUseCase.kt
  app/src/main/java/com/teampophory/pophory/feature/auth/model/OAuthToken.kt
  app/src/main/java/com/teampophory/pophory/feature/auth/social/KakaoAuthService.kt
  app/src/main/java/com/teampophory/pophory/feature/auth/social/OAuthService.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ✨ Feature

#63 KakaoAuthService ActivityComponent에서 주입할수 있게 바꾸기
  app/src/main/java/com/teampophory/pophory/config/di/OAuthModule.kt
Labels: 🐞 BugFix, 🐯 이현우

#57 [feature/myPage] myPage 진행상황 공유
  app/src/main/java/com/teampophory/pophory/data/repository/MyPageInfoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakeMyPageInfoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageDisplayItem.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageInfoState.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/network/MyPageInfoNetworkDataSource.kt
  app/src/main/java/com/teampophory/pophory/network/model/MyPageResponse.kt
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/img_mypage_empty_feed.xml
  app/src/main/res/drawable/img_mypage_profile.xml
  app/src/main/res/drawable/shape_store_bottom_text.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_mypage_feed.xml
  app/src/main/res/layout/item_mypage_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  core/common/src/main/java/com/teampophory/pophory/common/view/ViewExt.kt
Labels: 🦈서재원, ✨ Feature

#50 [feat/onBoarding] : 스플래시와 온보딩 뷰 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingData.kt
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/adapter/OnBoardingViewPagerAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpButtonInterface.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpDialogFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/StartPophoryActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
  app/src/main/res/drawable/bg_kakao_login_btn.xml
  app/src/main/res/drawable/bg_round_30dp_black.xml
  app/src/main/res/drawable/bg_round_30dp_white.xml
  app/src/main/res/drawable/bg_sign_up_edit_text_default.xml
  app/src/main/res/drawable/bg_sign_up_edit_text_error.xml
  app/src/main/res/drawable/bg_sign_up_edit_text_selected.xml
  app/src/main/res/drawable/bg_sign_up_tab_default.xml
  app/src/main/res/drawable/bg_sign_up_tab_selected.xml
  app/src/main/res/drawable/example_album_cover.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_edit_text_delete.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_pophory.xml
  app/src/main/res/drawable/ic_pophory_main_logo.xml
  app/src/main/res/drawable/round_album_select.xml
  app/src/main/res/drawable/round_dot_indicator.xml
  app/src/main/res/drawable/selector_sign_up_btn.xml
  app/src/main/res/drawable/selector_sign_up_tab.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_start_pophory.xml
  app/src/main/res/layout/fragment_sign_up_dialog.xml
  app/src/main/res/layout/fragment_sign_up_first.xml
  app/src/main/res/layout/fragment_sign_up_second.xml
  app/src/main/res/layout/fragment_sign_up_third.xml
  app/src/main/res/layout/item_album_cover_viewpager.xml
  app/src/main/res/layout/item_onboarding_viewpager.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🐣 안지현, ✨ Feature

#67 [feature/design-system] 디자인 시스템 정의 및 활용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingData.kt
  app/src/main/java/com/teampophory/pophory/feature/onboarding/adapter/OnBoardingViewPagerAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/res/color/selc_bottom_nav_item.xml
  app/src/main/res/drawable/bg_round_30dp_white.xml
  app/src/main/res/drawable/bg_sign_up_tab_default.xml
  app/src/main/res/drawable/bg_sign_up_tab_selected.xml
  app/src/main/res/drawable/selector_sign_up_btn.xml
  app/src/main/res/drawable/shape_bottom_nav.xml
  app/src/main/res/drawable/shape_store_bottom_text.xml
  app/src/main/res/font/pophory_font.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_start_pophory.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_sign_up_dialog.xml
  app/src/main/res/layout/fragment_sign_up_first.xml
  app/src/main/res/layout/fragment_sign_up_second.xml
  app/src/main/res/layout/fragment_sign_up_third.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_album_cover_viewpager.xml
  app/src/main/res/layout/item_horizontal_photo.xml
  app/src/main/res/layout/item_mypage_profile.xml
  app/src/main/res/layout/item_onboarding_viewpager.xml
  app/src/main/res/layout/item_store_pager.xml
  app/src/main/res/layout/item_vertical_photo.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/shape.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/type.xml
Labels: 🐯 이현우, ✨ Feature

#68 [feature/plugin-syntax-sugaring] plugin에서 id syntax sugaring 적용하기
  app/build.gradle.kts
  bottomnavigation/build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/gradle.properties
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/plugin.kt
  core/common/build.gradle.kts
Labels: 🐯 이현우, ⚙ Setting

#70 :sparkles: Add icon script
  icon/icon.sh
Labels: 🐯 이현우, ✨ Feature

#71 회원가입쪽 Refactoring
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpButtonInterface.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpDialogFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/StartPophoryActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
Labels: 🐯 이현우, 🔨 Refactor

#74 [feature/signup] 회원가입
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingData.kt
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/adapter/OnBoardingViewPagerAdapter.kt
  app/src/main/res/drawable/bg_sign_up_tab_default.xml
  app/src/main/res/drawable/img_congratuation.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_start_pophory.xml
  app/src/main/res/values/themes.xml
Labels: 🐣 안지현, ✨ Feature

#75 Add image files [skip ci]
  app/src/main/res/drawable-hdpi/ic_album_cover_collectbook.png
  app/src/main/res/drawable-hdpi/ic_album_cover_friends.png
  app/src/main/res/drawable-hdpi/ic_album_cover_love.png
  app/src/main/res/drawable-hdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-hdpi/ic_selector_collect_book.png
  app/src/main/res/drawable-hdpi/ic_selector_friends.png
  app/src/main/res/drawable-hdpi/ic_selector_love.png
  app/src/main/res/drawable-hdpi/ic_selector_myalbum.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_collectbook.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_friends.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_love.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-xhdpi/ic_selector_collect_book.png
  app/src/main/res/drawable-xhdpi/ic_selector_friends.png
  app/src/main/res/drawable-xhdpi/ic_selector_love.png
  app/src/main/res/drawable-xhdpi/ic_selector_myalbum.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_collectbook.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_friends.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_love.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-xxhdpi/ic_selector_collect_book.png
  app/src/main/res/drawable-xxhdpi/ic_selector_friends.png
  app/src/main/res/drawable-xxhdpi/ic_selector_love.png
  app/src/main/res/drawable-xxhdpi/ic_selector_myalbum.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_collectbook.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_friends.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_love.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-xxxhdpi/ic_selector_collect_book.png
  app/src/main/res/drawable-xxxhdpi/ic_selector_friends.png
  app/src/main/res/drawable-xxxhdpi/ic_selector_love.png
  app/src/main/res/drawable-xxxhdpi/ic_selector_myalbum.png
  app/src/main/res/drawable/ic_album_cover_collectbook.png
  app/src/main/res/drawable/ic_album_cover_friends.png
  app/src/main/res/drawable/ic_album_cover_love.png
  app/src/main/res/drawable/ic_album_cover_myalbum.png
  app/src/main/res/drawable/ic_selector_collect_book.png
  app/src/main/res/drawable/ic_selector_friends.png
  app/src/main/res/drawable/ic_selector_love.png
  app/src/main/res/drawable/ic_selector_myalbum.png
  icon/icon.sh
Labels: 🐯 이현우, ⚙ Setting

#76 [feature/setting-navigation-webview] WebView 네비게이션
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingData.kt
  app/src/main/java/com/teampophory/pophory/feature/on_boarding/adapter/OnBoardingViewPagerAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/webview/WebViewActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/webview/WebViewScreen.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ✨ Feature

#83 [feat/dialogFragment] : requestFeature 삭제
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpDialogFragment.kt
Labels: 🐣 안지현, ✨ Feature

#88 Feature/signup
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/StartPophoryActivity.kt
  app/src/main/res/drawable/kakao_login_button.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_start_pophory.xml
  app/src/main/res/layout/fragment_sign_up_dialog.xml
  app/src/main/res/layout/fragment_sign_up_first.xml
  app/src/main/res/layout/fragment_sign_up_second.xml
  app/src/main/res/layout/fragment_sign_up_third.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/type.xml
Labels: 🐣 안지현, ✨ Feature

#92 카카오 로그인 설정
  app/src/main/java/com/teampophory/pophory/data/network/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/AuthResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/SocialType.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/AuthService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/auth/DefaultAuthRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/auth/model/OAuthToken.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingActivity.kt
Labels: 🐯 이현우, ✨ Feature

#89 [Feature/mypage_ui] add VIEW_TYPE_EMPTY
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageDisplayItem.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/util/GridSpacingCustomDecoration.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
  app/src/main/res/drawable-xhdpi/ic_empty_feed.png
  app/src/main/res/drawable-xxhdpi/ic_empty_feed.png
  app/src/main/res/drawable-xxxhdpi/ic_empty_feed.png
  app/src/main/res/drawable/ic_empty_feed.png
  app/src/main/res/drawable/ic_empty_feed.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_mypage_empty.xml
  app/src/main/res/layout/item_mypage_profile.xml
Labels: 🦈서재원, 🔨 Refactor

#95 [feat/indicator]: Indicator 추가
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/teampophory/pophory/common/activity/ActivityExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/fragment/FragmentExt.kt
  core/common/src/main/java/com/teampophory/pophory/common/view/LoadingProgressIndicator.kt
  core/common/src/main/res/layout/fragment_progress_dialog.xml
Labels: 😼곽의진, ✨ Feature

#99 [Feature/store_album_cover] 앨범커버 이미지 리소스 변경 로직
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
  app/src/main/java/com/teampophory/pophory/util/AlbumCoverUtils.kt
  app/src/main/res/layout/item_store_pager.xml
Labels: 🦈서재원, ✨ Feature

#100 설정화면 Navigation + 탈퇴 API
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/data/network/service/AuthService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/auth/DefaultAuthRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
Labels: 🐯 이현우, ✨ Feature

#101 [feature/withdraw-fix] 탈퇴과정 이슈 fix + 회원가입 과정 fix
  app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/AuthService.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpApiFactory.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/network/model/SignUpRequest.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/signup/RetrofitSignUpNetwork.kt
Labels: 🐞 BugFix, 🐯 이현우

#98 [feature/album detail new]: 앨범 상세 화면 작업
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/albumsort/AlbumSortBottomSheet.kt
  app/src/main/java/com/teampophory/pophory/albumsort/AlbumSortType.kt
  app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/PhotoModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/album/PhotoListResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/AlbumService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumState.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailState.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListState.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/adapter/AlbumListAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/viewholder/AlbumViewHolder.kt
  app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
  app/src/main/java/com/teampophory/pophory/feature/album/viewholder/AlbumViewHolder.kt
  app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/network/PhotoNetworkDataSource.kt
  app/src/main/java/com/teampophory/pophory/network/model/PhotoListResponse.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
  app/src/main/res/drawable/bg_round_30dp_gray40.xml
  app/src/main/res/drawable/ic_add_black.xml
  app/src/main/res/drawable/ic_arrow_up_down.xml
  app/src/main/res/drawable/ic_bin_empty.xml
  app/src/main/res/drawable/ic_check_big.xml
  app/src/main/res/drawable/img_default_vertical_1.xml
  app/src/main/res/drawable/img_loading_horizontal.xml
  app/src/main/res/drawable/img_loading_vertical.xml
  app/src/main/res/drawable/shape_rect_radius_20_212121.xml
  app/src/main/res/layout/activity_album_detail.xml
  app/src/main/res/layout/activity_album_list.xml
  app/src/main/res/layout/bottom_sheet_album_sort.xml
  app/src/main/res/layout/fragment_album_delete_dialog.xml
  app/src/main/res/layout/item_horizontal_photo.xml
  app/src/main/res/layout/item_vertical_photo.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/type.xml
  core/common/src/main/java/com/teampophory/pophory/common/view/DialogFragmentExt.kt
Labels: 😼곽의진, ✨ Feature

#105 [feat/nickname_check]: add network 닉네임 중복체크
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/network/model/NicknameResponse.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/signup/RetrofitSignUpNetwork.kt
Labels: 🐣 안지현, 🦈서재원, ✨ Feature

#107 uri가 null일 때 사진 추가 화면으로 넘어가지 않게 하기
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
Labels: 🐞 BugFix, 🐯 이현우

#110 [Feature/fix qa] QA 수정사항
  app/src/main/java/com/teampophory/pophory/albumsort/AlbumSortBottomSheet.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/AuthResponse.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageDisplayItem.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpDialogFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/network/model/MyPageResponse.kt
  app/src/main/res/layout/bottom_sheet_album_sort.xml
  app/src/main/res/layout/fragment_album_delete_dialog.xml
  core/common/src/main/java/com/teampophory/pophory/common/context/ContextExt.kt
Labels: 🐞 BugFix, 😼곽의진

#111 회원가입 완료 후 PophoryStartActivity로 넘어가기
  app/src/main/java/com/teampophory/pophory/feature/signup/OnButtonStateChangeListener.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpButtonInterface.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/StartPophoryActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
  core/common/src/main/java/com/teampophory/pophory/common/lifecycle/Event.kt
Labels: 🐞 BugFix, 🐯 이현우

#113 [feature/loading-fix] Loading Fix + 배너 이미지 추가
  app/src/main/java/com/teampophory/pophory/albumsort/AlbumSortType.kt
  app/src/main/java/com/teampophory/pophory/feature/album/albumsort/AlbumSortBottomSheet.kt
  app/src/main/java/com/teampophory/pophory/feature/album/albumsort/AlbumSortType.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/res/drawable-hdpi/ic_banner.png
  app/src/main/res/drawable-xhdpi/ic_banner.png
  app/src/main/res/drawable-xxhdpi/ic_banner.png
  app/src/main/res/drawable-xxxhdpi/ic_banner.png
  app/src/main/res/drawable/ic_banner.png
  app/src/main/res/layout/item_mypage_profile.xml
Labels: 🐞 BugFix, 🐯 이현우

#115 [feature/auto-login] 자동 로그인 설정
  app/src/main/java/com/teampophory/pophory/data/local/DefaultPophoryDataStore.kt
  app/src/main/java/com/teampophory/pophory/data/local/PophoryDataStore.kt
  app/src/main/java/com/teampophory/pophory/data/repository/auth/AuthRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/auth/DefaultAuthRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/AutoLoginConfigureUseCase.kt
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/StartPophoryActivity.kt
Labels: 🐯 이현우, ✨ Feature

#116 [feature/configure-sentry-user] Sentry User Configuration
  app/src/main/java/com/teampophory/pophory/data/repository/auth/DefaultAuthRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/ConfigureMeUseCase.kt
  app/src/main/java/com/teampophory/pophory/feature/HomeViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
Labels: 🐯 이현우, ⚙ Setting

#114 [feature/qa album detail]: 앨범 리스트 내부에서 사진 업로드
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
Labels: 🐞 BugFix, 😼곽의진

#117 Feature/signup qa fix
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/res/layout/fragment_sign_up_second.xml
Labels: 🐞 BugFix, 🦈서재원

#121 [feature/proguard] Add proguard rules for minify
  app/proguard-rules.pro
Labels: 🐯 이현우, ⚙ Setting

#123 [feat/saved_state_viewmodel]: savedStateHandler를 viewmodel에서 활용하기
  app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/PhotoModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/PhotoService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoRaw.kt
  app/src/main/java/com/teampophory/pophory/network/PhotoNetworkDataSource.kt
Labels: 🐞 BugFix, 😼곽의진, ✨ Feature

#138 [feat/shared_element_transition]: Add Shared Element Activity Transit…
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/adapter/AlbumListAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/viewholder/AlbumViewHolder.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_album_detail.xml
  app/src/main/res/layout/item_horizontal_photo.xml
  app/src/main/res/layout/item_vertical_photo.xml
  app/src/main/res/values/themes.xml
Labels: 😼곽의진, ✨ Feature

#131 [feature/authenticator] 401 Authenticator 처리
  app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/MyPageModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/NetModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/PhotoModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/StoreModule.kt
  app/src/main/java/com/teampophory/pophory/config/di/qualifier/Auth.kt
  app/src/main/java/com/teampophory/pophory/data/network/authenticator/PophoryAuthenticator.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/TokenResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/RefreshApi.kt
  app/src/main/java/com/teampophory/pophory/domain/ConfigureMeUseCase.kt
  app/src/main/java/com/teampophory/pophory/feature/HomeViewModel.kt
Labels: 🐞 BugFix, 🐯 이현우

#137 [feature/home_reselected]: fragment 전환 방식변경
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
Labels: 🦈서재원, ✨ Feature

#143 [feature/rotate_block]: add rotate block
  app/src/main/java/com/teampophory/pophory/App.kt
Labels: 😼곽의진, 🦈서재원, ✨ Feature

#134 [feat/admob_reward]: reward video service 추가
  app/src/main/java/com/teampophory/pophory/config/ad/AdmobNativeAdService.kt
  app/src/main/java/com/teampophory/pophory/config/ad/AdmobRewardedAdService.kt
  app/src/main/java/com/teampophory/pophory/feature/sample/AdmobSampleActivity.kt
Labels: 😼곽의진, ✨ Feature

#152 [fix/error_text]: error 화면 text 변경
  core/common/src/main/res/layout/fragment_error_fullscreen.xml
Labels: 😼곽의진, ✨ Feature

#163 [Feature/presignedurl]: pre_signed_url 업로드 flow 제작
  app/src/main/java/com/teampophory/pophory/config/di/PhotoModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/photo/PhotoRequest.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/photo/S3ImageResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/PhotoService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/model/S3Image.kt
  app/src/main/java/com/teampophory/pophory/domain/repository/photo/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoViewModel.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/teampophory/pophory/common/okhttp/ResponseExt.kt
Labels: 😼곽의진, ✨ Feature

#165 [Feat/delete_refresh]: delete refresh 로직 추가
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/adapter/AlbumListAdapter.kt
Labels: 🐞 BugFix, 😼곽의진

#167 [Fix/image_size]: image_size get 로직 수정
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  core/common/src/main/java/com/teampophory/pophory/common/image/UriExt.kt
Labels: 🐞 BugFix, 😼곽의진

#168 [feature/limit-photo-size-format] 사진 용량 3MB, 포맷 JPEG 제한
  app/src/main/java/com/teampophory/pophory/config/di/NetModule.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/repository/photo/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoViewModel.kt
  core/common/src/main/java/com/teampophory/pophory/common/image/BitampRequestBody.kt
  core/common/src/main/java/com/teampophory/pophory/common/image/ContentUriReqeustBody.kt
  core/common/src/main/java/com/teampophory/pophory/common/image/UriExt.kt
Labels: 🐞 BugFix, 🐯 이현우

#173 [feature/fix-readme] README 최신화
  README.md
Labels: 🐯 이현우, 📃 Docs

#158 [Feature/mypage] 2차 스프린트 mypage 수정
  app/src/main/java/com/teampophory/pophory/config/di/MyPageModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/mypage/MyPageResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/MypageService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakeMyPageInfoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/my/DefaultMyPageRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/my/MyPageInfoRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/ConfigureMeUseCase.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageDisplayItem.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageInfoState.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/model/Profile.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/util/GridSpacingCustomDecoration.kt
  app/src/main/java/com/teampophory/pophory/network/MyPageNetworkDataSource.kt
  app/src/main/java/com/teampophory/pophory/network/model/MyPageResponse.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/mypage/RetrofitMyPageNetwork.kt
  app/src/main/res/drawable/bg_round_16dp_gray20.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/drawable/ic_profile_background.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: 🦈서재원, ✨ Feature

#176 [feature/image-rotate-issue-fix] 갤러리에서 가져온 이미지가 회전되어 보이는 이슈 해소
  app/build.gradle.kts
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  gradle/libs.versions.toml
Labels: 🐞 BugFix, 🐯 이현우, 🦈서재원

#160 [Feature/store] 내 서랍(store) 2차 스프린트 기능구현
  app/src/main/java/com/teampophory/pophory/config/di/StoreModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/photo/PhotoRequest.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/share/StoreResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/PhotoService.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/StoreSerivce.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/store/DefaultStoreRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/store/StoreRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/repository/photo/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/model/AlbumItem.kt
  app/src/main/java/com/teampophory/pophory/network/StoreNetworkDataSource.kt
  app/src/main/java/com/teampophory/pophory/network/retrofit/store/RetrofitStoreNetwork.kt
  app/src/main/res/drawable/bg_seekbar_custom.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_thumb_default.xml
  app/src/main/res/drawable/ic_thumb_full.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/values/strings.xml
Labels: 🦈서재원, ✨ Feature

#186 Feature/image item stroke
  app/src/main/res/drawable/img_default_vertical_1.xml
  app/src/main/res/drawable/img_loading_vertical.xml
  app/src/main/res/layout/activity_album_list.xml
Labels: 🐞 BugFix, 😼곽의진

#184 [Feature/photo detail-UI] 2차 스프린트 photo detail migration 및 ui 수정
  app/src/main/java/com/teampophory/pophory/data/network/model/album/PhotoListResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/PhotoService.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
  app/src/main/res/drawable/bg_round_30dp_gray20.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/ic_share_photo.xml
  app/src/main/res/drawable/shape_rect_radius_20_white.xml
  app/src/main/res/layout/activity_album_detail.xml
  app/src/main/res/layout/fragment_album_delete_dialog.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: 🦈서재원, ✨ Feature

#187 [Feature/story] 포릿 이야기 엑티비티, 웹뷰 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/story/StoryActivity.kt
  app/src/main/res/color/selc_bottom_nav_item.xml
  app/src/main/res/drawable/ic_profile_backgorund.xml
  app/src/main/res/drawable/ic_profile_background.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/activity_story.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_store_pager.xml
  app/src/main/res/values/strings.xml
Labels: 🦈서재원, ✨ Feature

#193 [feature/change_url]: 서비스 이용약관 및 개인정보 처리방침 url change
  app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
Labels: 🐞 BugFix, 😼곽의진

#172 [Feature/share] 공유하기 화면 제작완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/config/di/ShareModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/ShareNetworkDataSource.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/share/ShareResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/store/StoreResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/RetrofitShareNetwork.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/StoreSerivce.kt
  app/src/main/java/com/teampophory/pophory/data/repository/share/DefaultShareRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/share/ShareRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/store/DefaultStoreRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/store/StoreRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/share/ShareState.kt
  app/src/main/java/com/teampophory/pophory/feature/share/ShareViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/share/adapter/ShareAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/share/model/PhotoItem.kt
  app/src/main/res/drawable-hdpi/img_onboarding01.png
  app/src/main/res/drawable-hdpi/img_onboarding02.png
  app/src/main/res/drawable-hdpi/img_onboarding03.png
  app/src/main/res/drawable-xhdpi/img_onboarding01.png
  app/src/main/res/drawable-xhdpi/img_onboarding02.png
  app/src/main/res/drawable-xhdpi/img_onboarding03.png
  app/src/main/res/drawable-xhdpi/img_onboarding04.png
  app/src/main/res/drawable-xxhdpi/img_onboarding01.png
  app/src/main/res/drawable-xxhdpi/img_onboarding02.png
  app/src/main/res/drawable-xxhdpi/img_onboarding03.png
  app/src/main/res/drawable-xxhdpi/img_onboarding04.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding01.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding02.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding03.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding04.png
  app/src/main/res/drawable/img_onboarding01.png
  app/src/main/res/drawable/img_onboarding02.png
  app/src/main/res/drawable/img_onboarding03.png
  app/src/main/res/drawable/img_onboarding04.png
  app/src/main/res/drawable/square_photo_select.xml
  app/src/main/res/layout/activity_album_list.xml
  app/src/main/res/layout/activity_share.xml
  app/src/main/res/layout/item_share_photo.xml
  app/src/main/res/values/strings.xml
Labels: 🦈서재원, ✨ Feature

#197 Bump Kotlin, compose version
  README.md
  build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/ComposePlugin.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ⚙ Setting

#190 [feature/add_photo]: add_photo view 변경
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/res/drawable/bg_round_100dp_black.xml
  app/src/main/res/layout/activity_add_photo.xml
  app/src/main/res/layout/activity_album_list.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/type.xml
Labels: 🐞 BugFix, 😼곽의진

#157 Feature refactor signup
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpSecondFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
  app/src/main/res/drawable/ic_selector_theme_family.xml
  app/src/main/res/drawable/ic_selector_theme_friends.xml
  app/src/main/res/drawable/ic_selector_theme_love.xml
  app/src/main/res/drawable/ic_selector_theme_me.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_start_pophory.xml
  app/src/main/res/layout/fragment_sign_up_first.xml
  app/src/main/res/layout/fragment_sign_up_second.xml
  app/src/main/res/layout/fragment_sign_up_third.xml
  app/src/main/res/navigation/nav_signup_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐣 안지현, ✨ Feature

#199 커버 이미지 추가 및 커버 번호 수정 [skip ci]
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpThirdFragment.kt
  app/src/main/java/com/teampophory/pophory/util/AlbumCoverUtils.kt
  app/src/main/res/drawable-hdpi/ic_album_cover_collectbook.png
  app/src/main/res/drawable-hdpi/ic_album_cover_friends.png
  app/src/main/res/drawable-hdpi/ic_album_cover_love.png
  app/src/main/res/drawable-hdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_family_1.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_family_2.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_friends_1.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_friends_2.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_love_1.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_love_2.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_me_1.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_me_2.png
  app/src/main/res/drawable-xhdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_family_1.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_family_2.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_friends_1.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_friends_2.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_love_1.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_love_2.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_me_1.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_me_2.png
  app/src/main/res/drawable-xxhdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_family_1.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_family_2.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_friends_1.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_friends_2.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_love_1.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_love_2.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_me_1.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_me_2.png
  app/src/main/res/drawable-xxxhdpi/ic_album_cover_myalbum.png
  app/src/main/res/drawable/ic_album_cover_family_1.png
  app/src/main/res/drawable/ic_album_cover_family_2.png
  app/src/main/res/drawable/ic_album_cover_friends_1.png
  app/src/main/res/drawable/ic_album_cover_friends_2.png
  app/src/main/res/drawable/ic_album_cover_love_1.png
  app/src/main/res/drawable/ic_album_cover_love_2.png
  app/src/main/res/drawable/ic_album_cover_me_1.png
  app/src/main/res/drawable/ic_album_cover_me_2.png
Labels: 🦈서재원, ✨ Feature

#179 [feature/share-image] 사진 공유 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/config/di/ShareModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/share/AcceptShareResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/share/SharePhotoResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/share/ShareResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/ShareService.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/share/model/PhotoItem.kt
  app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveSharedImageActivity.kt
  app/src/main/res/drawable/ic_card_logo.xml
  app/src/main/res/layout/activity_receive_shared_image.xml
  core/common/src/main/java/com/teampophory/pophory/common/image/UriExt.kt
  gradle/libs.versions.toml
Labels: 🐯 이현우, ✨ Feature

#203 [feature/code-refactor-file-move] 폴더링 고치기
  app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/NicknameResponse.kt
  app/src/main/java/com/teampophory/pophory/data/network/model/auth/SignUpRequest.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/RetrofitSignUpNetwork.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/home/HomeViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
Labels: 🐯 이현우, ⚙ Setting

#159 [Feature/album viewpager]: AlbumCover 수정 화면 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampophory/pophory/data/network/model/album/AlbumCoverChangeRequest.kt
  app/src/main/java/com/teampophory/pophory/data/network/service/PhotoService.kt
  app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/domain/repository/photo/PhotoRepository.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditViewModel.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumEditState.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/adapter/AlbumCoverEditAdapter.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/adapter/AlbumCoverEditViewHolder.kt
  app/src/main/java/com/teampophory/pophory/feature/album/cover/model/AlbumCoverItem.kt
  app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
  app/src/main/java/com/teampophory/pophory/util/HorizontalMarginItemDecoration.kt
  app/src/main/res/drawable/ic_edit_album.xml
  app/src/main/res/layout/activity_album_cover_edit.xml
  app/src/main/res/layout/fragment_store.xml
  app/src/main/res/layout/item_album_cover_viewpager.xml
  app/src/main/res/layout/item_store_pager.xml
  app/src/main/res/values/strings.xml
Labels: 😼곽의진, ✨ Feature

#206 [Fix/share-check] Intent 이후 체크 표시 해제 이슈 해결
  app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
  app/src/main/res/layout/fragment_store.xml
Labels: 🐞 BugFix, 🦈서재원

#207 [feature/onboarding-design-qa] 온보딩, 회원가입, 홈화면(앨범) QA 반영
  app/src/main/java/com/teampophory/pophory/feature/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_start_pophory.xml
  app/src/main/res/layout/fragment_sign_up_third.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 BugFix, 🐯 이현우

#209 [feature/photo_add_error]: 크래시 해결
  app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
Labels: 🐞 BugFix, 😼곽의진

#212 [fix/album_edit_error]: 크래시 해결
  app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
  app/src/main/res/layout/activity_album_cover_edit.xml
Labels: 🐞 BugFix, 😼곽의진

#210 [Fix/my page error]: my page 라이팅 및 색상 수정
  app/src/main/res/layout/dialog_common_one_button.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 BugFix, 😼곽의진

#213 [feature/setting-qa] 설정화면 QA
  app/src/main/java/com/teampophory/pophory/feature/setting/TermScreen.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/LogoutDialog.kt
  app/src/main/java/com/teampophory/pophory/feature/setting/component/WithdrawDialog.kt
Labels: 🐞 BugFix, 🐯 이현우

#215 [fix/photo_list_empty]: photo_list_empty 뷰 수정
  app/src/main/res/layout/activity_album_list.xml
Labels: 🐞 BugFix, 😼곽의진

#216 [Fix/sign up popup text]: sign up modal text 변경
  app/src/main/res/layout/fragment_sign_up_dialog.xml
Labels: 🐞 BugFix, 😼곽의진

#219 [feature/phopory-team-image] UI 포포리팀 PNG 추가
  app/src/main/java/com/teampophory/pophory/feature/setting/TeamScreen.kt
  app/src/main/res/drawable-xhdpi/img_team.png
  app/src/main/res/drawable-xxhdpi/img_team.png
  app/src/main/res/drawable-xxxhdpi/img_team.png
  app/src/main/res/drawable/img_team.png
Labels: 🦈서재원, ✨ Feature

#221 가입 완료 화면에서 홈으로 갈 때 새 task로 이동
  app/src/main/java/com/teampophory/pophory/feature/signup/StartPophoryActivity.kt
  firebase/releaseNote.txt
Labels: 🐞 BugFix, 🐯 이현우

#222 자기 사진 공유 시도 시 차단
  app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveSharedImageActivity.kt
Labels: 🐞 BugFix, 🐯 이현우

#225 미로그인 시 사진공유할 시 앱 크래시날 수 있는 부분 수정
  app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
Labels: 🐞 BugFix, 🐯 이현우

#226 [fix/delete_error]: 사진 삭제 오류 수정
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
  app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
Labels: 🐞 BugFix, 😼곽의진

#227 Fix error when app preferences create
  app/src/main/java/com/teampophory/pophory/config/di/PreferencesModule.kt
Labels: 🐞 BugFix, 🐯 이현우
